name: Run Python Bot

on:
  schedule:
    - cron: '*/15 * * * *'  # هر 15 دقیقه اجرا میشه
  workflow_dispatch:  # اجرا دستی هم داشته باشه

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.1  # نسخه درست

      - name: Install dependencies
        run: |
          pip install requests mnemonic eth-account

      - name: Run bot
        run: python main.py
